name: SimpleExploitFixer
folia-supported: true 
version: ${project.version}
main: me.krymz0n.simpleexploitfixer.Main
api-version: 1.16
authors: [ KRYMZ0N ]
description: A simple exploit fixer made for the 3b3t.me minecrafts server. Making a new plugin every time a new exploit comes along is fucking annoying.
website: www.3b3t.me
depend:
  - ProtocolLib

commands:
  sef:
    description: a
